### ISSUE TITLE
[bug]  app crash when searching for conjugation of verbe "battre" 

### ISSUE THREAD

**Issue by allan-simon** [allan-simon/verbiste-android#4]

**Comment by mvhulten** [comment]
The just released 1.0 in F-Droid crashes when searching for any (de)conjugation. On CyanogenMod 13.0.

**Comment by allan-simon** [comment]
Wow, great I didn't know it was on F-droid, Is there a way for you to provide me some logs ? Which versio of android is it ?

**Comment by allan-simon** [comment]
hmmm I just tried to install from f-droid, and indeed it crash for me too,  looking to the size of the APK i think they've forgotten to include the database in it :(

**Comment by allan-simon** [comment]
I've reported the issue on f-droid side, to see how i can include it in the build process of the apk on their side.

**Comment by mvhulten** [comment]
Great, let's hope they can fix this!

**Comment by allan-simon** [comment]
it works correctly now if you uninstall/redownload it :)

**Comment by gargamel17** [comment]
Hello, problem still present in version 1.2 downloaded from F-Droid.
![capture](https://user-images.githubusercontent.com/44755327/122402828-221bac80-cf7e-11eb-8e79-3398919dc200.png)
Here is the log generated  (os : LOS 18.1)
FATAL EXCEPTION: main
Process: com.allansimon.verbisteandroid, PID: 23744
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.allansimon.verbisteandroid/com.allansimon.verbisteandroid.DisplayConjugationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at com.allansimon.verbisteandroid.DisplayConjugationActivity.addConjugatedColumn(DisplayConjugationActivity.java:161)
	at com.allansimon.verbisteandroid.DisplayConjugationActivity.onCreate(DisplayConjugationActivity.java:118)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)

**Comment by allan-simon** [comment]
I've rewrote the app there https://github.com/allan-simon/verbiste-cordova/ , it should be easier for me to maintain , I hope it can get integrated in f-droid too :)
